SHELL := /bin/sh

MY_BASE := $(HOME)
MYLIB := -L$(MY_BASE)/lib/iris
MYINCLUDE := -I$(MY_BASE)/local/include
MYFLAGS := -O2 -DIRIS

LDFLAGS := $(MYLIB) -lEHaudio++ -ldist -lEHnet++ -leclib

C++ := g++
CC  := gcc

C++FLAGS := $(MYINCLUDE) $(MYFLAGS)
CFLAGS := -O2 -pipe

default : iris/libEHaudio++.a

iris/libEHaudio++.a : StrChunk.o StrChunkio.o StrFDPlug.o StreamFDModule.o \
                  StreamModule.o StreamSplitter.o SocketModule.o \
                  SockListenModule.o
	ar ruv iris/libEHaudio++.a $?
	ranlib iris/libEHaudio++.a
	ranlib iris/libEHaudio++.a

server : server.o lib/libEHaudio++.a
	$(C++) server.o $(LDFLAGS) -o server

testAudFile : testAudFile.o lib/libEHaudio++.a
	$(C++) tesstAudFile.o $(LDFLAGS) -o testAudFile

testdist : testdist.o lib/libEHaudio++.a
	$(C++) testdist.o $(LDFLAGS) -o testdist

teststr : teststr.o lib/libEHaudio++.a
	$(C++) teststr.o $(LDFLAGS) -o teststr

testchunk : testchunk.o lib/libEHaudio++.a
	$(C++) testchunk.o $(LDFLAGS) -o testchunk

depend :
	depend.awk < GNUmakefile >GNUmakefile.new
	echo '## Heh heh heh' >>GNUmakefile.new
	echo >>GNUmakefile.new
	g++  $(C++FLAGS) -M *.cc >>GNUmakefile.new
#	gcc $(CFLAGS) -MM *.c >>GNUmakefile.new
	mv GNUmakefile GNUmakefile~
	mv GNUmakefile.new GNUmakefile

## Do not remove this line, or the next, they are needed for make depend
## Heh heh heh

SockListenModule.oc: SockListenModule.cc 
SockListenModule.oc: /circle/s28/hopper/local/include/EHaudio++/SockListenModule.h 
SockListenModule.oc: /circle/s28/hopper/local/include/EHaudio++/SocketModule.h 
SockListenModule.oc: /circle/s28/hopper/local/include/EHaudio++/StreamFDModule.h 
SockListenModule.oc: /circle/s28/hopper/local/include/EHaudio++/StreamModule.h 
SockListenModule.oc: /circle/s28/hopper/local/include/Dispatch/iohandler.h 
SockListenModule.oc: /circle/s28/hopper/local/include/Dispatch/dpdefs.h 
SockListenModule.oc: /circle/s28/hopper/local/include/EHnet++/SocketAddress.h 
SockListenModule.oc: /circle/s28/hopper/local/include/ibm++/object.h 
SockListenModule.oc: /circle/s28/hopper/local/include/ibm++/clsdef.h 
SockListenModule.oc: /circle/s28/hopper/local/include/ibm++/types.h 
SockListenModule.oc: /circle/s28/hopper/local/include/EHaudio++/StrChunk.h 
SockListenModule.oc: /circle/s28/hopper/local/include/ibm/MulRef.h 
SockListenModule.oc: /usr/include/assert.h 
SockListenModule.oc: /usr/include/stdlib.h 
SockListenModule.oc: /circle/s28/hopper/local/include/EHaudio++/ChunkType.h 
SockListenModule.oc: /circle/s28/hopper/local/include/ibm++/stringc.h 
SockListenModule.oc: /circle/s28/hopper/local/include/ibm++/sortable.h 
SockListenModule.oc: /circle/s28/hopper/local/include/ibm++/MulRef.h 
SockListenModule.oc: /usr/include/string.h 
SockListenModule.oc: /circle/s28/hopper/local/include/ibm++/strinlne.h 
SockListenModule.oc: /circle/s28/hopper/local/include/EHnet++/InetAddress.h 
SockListenModule.oc: /usr/include/sys/types.h 
SockListenModule.oc: /usr/include/netinet/in.h 
SockListenModule.oc: /circle/s28/hopper/local/include/Dispatch/dispatcher.h 
SockListenModule.oc: /usr/include/fcntl.h 
SockListenModule.oc: /usr/include/sys/fcntl.h 
SockListenModule.oc: /usr/include/sys/socket.h 
SockListenModule.oc: /usr/include/errno.h 
SockListenModule.oc: /usr/include/sys/errno.h 
SockListenModule.oc: /usr/include/CC/iostream.h 
SockListenModule.oc: /usr/include/memory.h 
SockListenModule.oc: /usr/include/stddef.h 
SocketModule.oc: SocketModule.cc 
SocketModule.oc: /circle/s28/hopper/local/include/EHaudio++/SocketModule.h 
SocketModule.oc: /circle/s28/hopper/local/include/EHaudio++/StreamFDModule.h 
SocketModule.oc: /circle/s28/hopper/local/include/EHaudio++/StreamModule.h 
SocketModule.oc: /circle/s28/hopper/local/include/Dispatch/iohandler.h 
SocketModule.oc: /circle/s28/hopper/local/include/Dispatch/dpdefs.h 
SocketModule.oc: /circle/s28/hopper/local/include/EHnet++/SocketAddress.h 
SocketModule.oc: /circle/s28/hopper/local/include/ibm++/object.h 
SocketModule.oc: /circle/s28/hopper/local/include/ibm++/clsdef.h 
SocketModule.oc: /circle/s28/hopper/local/include/ibm++/types.h 
SocketModule.oc: /usr/include/fcntl.h 
SocketModule.oc: /usr/include/sys/types.h 
SocketModule.oc: /usr/include/sys/fcntl.h 
SocketModule.oc: /usr/include/sys/socket.h 
SocketModule.oc: /usr/include/errno.h 
SocketModule.oc: /usr/include/sys/errno.h 
StrChunk.oc: StrChunk.cc 
StrChunk.oc: /circle/s28/hopper/local/include/EHaudio++/StrChunk.h 
StrChunk.oc: /circle/s28/hopper/local/include/ibm/MulRef.h 
StrChunk.oc: /circle/s28/hopper/local/include/ibm++/object.h 
StrChunk.oc: /circle/s28/hopper/local/include/ibm++/clsdef.h 
StrChunk.oc: /circle/s28/hopper/local/include/ibm++/types.h 
StrChunk.oc: /usr/include/assert.h 
StrChunk.oc: /usr/include/stdlib.h 
StrChunk.oc: /circle/s28/hopper/local/include/EHaudio++/ChunkType.h 
StrChunk.oc: /usr/include/CC/iostream.h 
StrChunk.oc: /usr/include/memory.h 
StrChunk.oc: /usr/include/stddef.h 
StrChunkio.oc: StrChunkio.cc 
StrChunkio.oc: /circle/s28/hopper/local/include/EHaudio++/StrChunk.h 
StrChunkio.oc: /circle/s28/hopper/local/include/ibm/MulRef.h 
StrChunkio.oc: /circle/s28/hopper/local/include/ibm++/object.h 
StrChunkio.oc: /circle/s28/hopper/local/include/ibm++/clsdef.h 
StrChunkio.oc: /circle/s28/hopper/local/include/ibm++/types.h 
StrChunkio.oc: /usr/include/assert.h 
StrChunkio.oc: /usr/include/stdlib.h 
StrChunkio.oc: /circle/s28/hopper/local/include/EHaudio++/ChunkType.h 
StrChunkio.oc: /usr/include/unistd.h 
StrChunkio.oc: /usr/include/sys/types.h 
StrChunkio.oc: /usr/include/time.h 
StrChunkio.oc: /usr/include/utime.h 
StrChunkio.oc: /usr/include/sys/syssgi.h 
StrFDPlug.oc: StrFDPlug.cc 
StrFDPlug.oc: /circle/s28/hopper/local/include/EHaudio++/StreamFDModule.h 
StrFDPlug.oc: /circle/s28/hopper/local/include/EHaudio++/StreamModule.h 
StrFDPlug.oc: /circle/s28/hopper/local/include/Dispatch/iohandler.h 
StrFDPlug.oc: /circle/s28/hopper/local/include/Dispatch/dpdefs.h 
StrFDPlug.oc: /circle/s28/hopper/local/include/Dispatch/dispatcher.h 
StrFDPlug.oc: /circle/s28/hopper/local/include/EHaudio++/StrChunk.h 
StrFDPlug.oc: /circle/s28/hopper/local/include/ibm/MulRef.h 
StrFDPlug.oc: /circle/s28/hopper/local/include/ibm++/object.h 
StrFDPlug.oc: /circle/s28/hopper/local/include/ibm++/clsdef.h 
StrFDPlug.oc: /circle/s28/hopper/local/include/ibm++/types.h 
StrFDPlug.oc: /usr/include/assert.h 
StrFDPlug.oc: /usr/include/stdlib.h 
StrFDPlug.oc: /circle/s28/hopper/local/include/EHaudio++/ChunkType.h 
StrFDPlug.oc: /usr/include/unistd.h 
StrFDPlug.oc: /usr/include/sys/types.h 
StrFDPlug.oc: /usr/include/time.h 
StrFDPlug.oc: /usr/include/utime.h 
StrFDPlug.oc: /usr/include/sys/syssgi.h 
StrFDPlug.oc: /usr/include/CC/iostream.h 
StrFDPlug.oc: /usr/include/memory.h 
StrFDPlug.oc: /usr/include/stddef.h 
StrFDPlug.oc: /usr/include/errno.h 
StrFDPlug.oc: /usr/include/sys/errno.h 
StreamFDModule.oc: StreamFDModule.cc 
StreamFDModule.oc: /circle/s28/hopper/local/include/EHaudio++/StreamFDModule.h 
StreamFDModule.oc: /circle/s28/hopper/local/include/EHaudio++/StreamModule.h 
StreamFDModule.oc: /circle/s28/hopper/local/include/Dispatch/iohandler.h 
StreamFDModule.oc: /circle/s28/hopper/local/include/Dispatch/dpdefs.h 
StreamFDModule.oc: /circle/s28/hopper/local/include/EHaudio++/StrChunk.h 
StreamFDModule.oc: /circle/s28/hopper/local/include/ibm/MulRef.h 
StreamFDModule.oc: /circle/s28/hopper/local/include/ibm++/object.h 
StreamFDModule.oc: /circle/s28/hopper/local/include/ibm++/clsdef.h 
StreamFDModule.oc: /circle/s28/hopper/local/include/ibm++/types.h 
StreamFDModule.oc: /usr/include/assert.h 
StreamFDModule.oc: /usr/include/stdlib.h 
StreamFDModule.oc: /circle/s28/hopper/local/include/EHaudio++/ChunkType.h 
StreamFDModule.oc: /circle/s28/hopper/local/include/ibm++/stringc.h 
StreamFDModule.oc: /circle/s28/hopper/local/include/ibm++/sortable.h 
StreamFDModule.oc: /circle/s28/hopper/local/include/ibm++/MulRef.h 
StreamFDModule.oc: /usr/include/string.h 
StreamFDModule.oc: /circle/s28/hopper/local/include/ibm++/strinlne.h 
StreamFDModule.oc: /usr/include/sys/types.h 
StreamFDModule.oc: /usr/include/sys/stat.h 
StreamFDModule.oc: /usr/include/errno.h 
StreamFDModule.oc: /usr/include/sys/errno.h 
StreamModule.oc: StreamModule.cc 
StreamModule.oc: /circle/s28/hopper/local/include/EHaudio++/StreamModule.h 
StreamSplitter.oc: StreamSplitter.cc 
StreamSplitter.oc: /circle/s28/hopper/local/include/EHaudio++/StreamSplitter.h 
StreamSplitter.oc: /circle/s28/hopper/local/include/EHaudio++/StreamModule.h 
StreamSplitter.oc: /circle/s28/hopper/local/include/EHaudio++/StrChunk.h 
StreamSplitter.oc: /circle/s28/hopper/local/include/ibm/MulRef.h 
StreamSplitter.oc: /circle/s28/hopper/local/include/ibm++/object.h 
StreamSplitter.oc: /circle/s28/hopper/local/include/ibm++/clsdef.h 
StreamSplitter.oc: /circle/s28/hopper/local/include/ibm++/types.h 
StreamSplitter.oc: /usr/include/assert.h 
StreamSplitter.oc: /usr/include/stdlib.h 
StreamSplitter.oc: /circle/s28/hopper/local/include/EHaudio++/ChunkType.h 
StreamSplitter.oc: /usr/include/CC/iostream.h 
StreamSplitter.oc: /usr/include/memory.h 
StreamSplitter.oc: /usr/include/stddef.h 
StreamSplitter.oc: /circle/s28/hopper/local/include/Dispatch/dispatcher.h 
StreamSplitter.oc: /circle/s28/hopper/local/include/Dispatch/dpdefs.h 
server.oc: server.cc 
server.oc: /circle/s28/hopper/local/include/EHaudio++/SockListenModule.h 
server.oc: /circle/s28/hopper/local/include/EHaudio++/SocketModule.h 
server.oc: /circle/s28/hopper/local/include/EHaudio++/StreamFDModule.h 
server.oc: /circle/s28/hopper/local/include/EHaudio++/StreamModule.h 
server.oc: /circle/s28/hopper/local/include/Dispatch/iohandler.h 
server.oc: /circle/s28/hopper/local/include/Dispatch/dpdefs.h 
server.oc: /circle/s28/hopper/local/include/EHnet++/SocketAddress.h 
server.oc: /circle/s28/hopper/local/include/ibm++/object.h 
server.oc: /circle/s28/hopper/local/include/ibm++/clsdef.h 
server.oc: /circle/s28/hopper/local/include/ibm++/types.h 
server.oc: /circle/s28/hopper/local/include/EHaudio++/StrChunk.h 
server.oc: /circle/s28/hopper/local/include/ibm/MulRef.h 
server.oc: /usr/include/assert.h 
server.oc: /usr/include/stdlib.h 
server.oc: /circle/s28/hopper/local/include/EHaudio++/ChunkType.h 
server.oc: /circle/s28/hopper/local/include/EHnet++/InetAddress.h 
server.oc: /circle/s28/hopper/local/include/ibm++/stringc.h 
server.oc: /circle/s28/hopper/local/include/ibm++/sortable.h 
server.oc: /circle/s28/hopper/local/include/ibm++/MulRef.h 
server.oc: /usr/include/string.h 
server.oc: /circle/s28/hopper/local/include/ibm++/strinlne.h 
server.oc: /usr/include/sys/types.h 
server.oc: /usr/include/netinet/in.h 
server.oc: /circle/s28/hopper/local/include/Dispatch/dispatcher.h 
server.oc: /usr/include/CC/iostream.h 
server.oc: /usr/include/memory.h 
server.oc: /usr/include/stddef.h 
testchunk.oc: testchunk.cc 
testchunk.oc: /circle/s28/hopper/local/include/EHaudio++/StrChunk.h 
testchunk.oc: /circle/s28/hopper/local/include/ibm/MulRef.h 
testchunk.oc: /circle/s28/hopper/local/include/ibm++/object.h 
testchunk.oc: /circle/s28/hopper/local/include/ibm++/clsdef.h 
testchunk.oc: /circle/s28/hopper/local/include/ibm++/types.h 
testchunk.oc: /usr/include/assert.h 
testchunk.oc: /usr/include/stdlib.h 
testchunk.oc: /circle/s28/hopper/local/include/EHaudio++/ChunkType.h 
testchunk.oc: /usr/include/unistd.h 
testchunk.oc: /usr/include/sys/types.h 
testchunk.oc: /usr/include/time.h 
testchunk.oc: /usr/include/utime.h 
testchunk.oc: /usr/include/sys/syssgi.h 
testchunk.oc: /usr/include/CC/iostream.h 
testchunk.oc: /usr/include/memory.h 
testchunk.oc: /usr/include/stddef.h 
testchunk.oc: /usr/include/fcntl.h 
testchunk.oc: /usr/include/sys/fcntl.h 
testchunk.oc: /usr/include/errno.h 
testchunk.oc: /usr/include/sys/errno.h 
testdist.oc: testdist.cc 
testdist.oc: /circle/s28/hopper/local/include/Dispatch/dispatcher.h 
testdist.oc: /circle/s28/hopper/local/include/Dispatch/dpdefs.h 
testdist.oc: /circle/s28/hopper/local/include/Dispatch/iohandler.h 
testdist.oc: /circle/s28/hopper/local/include/ibm/stringc.h 
testdist.oc: /circle/s28/hopper/local/include/ibm++/sortable.h 
testdist.oc: /circle/s28/hopper/local/include/ibm++/object.h 
testdist.oc: /circle/s28/hopper/local/include/ibm++/clsdef.h 
testdist.oc: /circle/s28/hopper/local/include/ibm++/types.h 
testdist.oc: /circle/s28/hopper/local/include/ibm++/MulRef.h 
testdist.oc: /usr/include/string.h 
testdist.oc: /circle/s28/hopper/local/include/ibm++/strinlne.h 
testdist.oc: /usr/include/CC/iostream.h 
testdist.oc: /usr/include/memory.h 
testdist.oc: /usr/include/stddef.h 
teststr.oc: teststr.cc 
teststr.oc: /circle/s28/hopper/local/include/EHaudio++/SocketModule.h 
teststr.oc: /circle/s28/hopper/local/include/EHaudio++/StreamFDModule.h 
teststr.oc: /circle/s28/hopper/local/include/EHaudio++/StreamModule.h 
teststr.oc: /circle/s28/hopper/local/include/Dispatch/iohandler.h 
teststr.oc: /circle/s28/hopper/local/include/Dispatch/dpdefs.h 
teststr.oc: /circle/s28/hopper/local/include/EHnet++/SocketAddress.h 
teststr.oc: /circle/s28/hopper/local/include/ibm++/object.h 
teststr.oc: /circle/s28/hopper/local/include/ibm++/clsdef.h 
teststr.oc: /circle/s28/hopper/local/include/ibm++/types.h 
teststr.oc: /circle/s28/hopper/local/include/EHnet++/InetAddress.h 
teststr.oc: /circle/s28/hopper/local/include/ibm++/stringc.h 
teststr.oc: /circle/s28/hopper/local/include/ibm++/sortable.h 
teststr.oc: /circle/s28/hopper/local/include/ibm++/MulRef.h 
teststr.oc: /usr/include/string.h 
teststr.oc: /circle/s28/hopper/local/include/ibm++/strinlne.h 
teststr.oc: /usr/include/sys/types.h 
teststr.oc: /usr/include/netinet/in.h 
teststr.oc: /circle/s28/hopper/local/include/EHaudio++/StreamSplitter.h 
teststr.oc: /circle/s28/hopper/local/include/Dispatch/dispatcher.h 
teststr.oc: /usr/include/CC/iostream.h 
teststr.oc: /usr/include/memory.h 
teststr.oc: /usr/include/stddef.h 
teststr.oc: /usr/include/unistd.h 
teststr.oc: /usr/include/time.h 
teststr.oc: /usr/include/utime.h 
teststr.oc: /usr/include/sys/syssgi.h 
teststr.oc: /usr/include/fcntl.h 
teststr.oc: /usr/include/sys/fcntl.h 
